"""
t5_optimize_captions.py

This script post-processes the captions generated by t3_generate_dataset_4view.py
(using build_caption_from_combo in t4_lpc_caption_utils.py).

It:
  - reads captions.csv
  - parses the core description phrases
  - rewrites each caption into a shorter and more structured style
  - preserves ALL color/material/style information from t4
  - writes the result to captions_optimized.csv

Input  : pixel_character_dataset/processed/dataset_4view/captions.csv
Output : pixel_character_dataset/processed/dataset_4view/captions_optimized.csv

New caption template (single line, LoRA-friendly, fixed prefix):

    lpc-style pixel art character, with <body>,
    wearing <torso+legs+clothing>,
    with <hair>,
    with <gear and weapons>,
    4-view sprite sheet (front/back/left/right), sharp small pixel art, no anti-aliasing

(Actual output is a single line; line breaks above are for documentation only.)
"""

import csv
from pathlib import Path

# ----------------- paths -----------------

SCRIPT_DIR = Path(__file__).resolve().parent          # PIXEL-T2I/scripts
ROOT = SCRIPT_DIR.parent                              # PIXEL-T2I

DATASET_ROOT = ROOT / "pixel_character_dataset"
PROCESSED_ROOT = DATASET_ROOT / "processed" / "dataset_4view"

CAPTION_CSV_IN  = PROCESSED_ROOT / "captions.csv"
CAPTION_CSV_OUT = PROCESSED_ROOT / "captions_optimized.csv"


# ----------------- helpers: generic utilities -----------------

def join_with_and(items: list[str]) -> str:
    """
    Join a list of phrases in a natural way:
      ["A"] -> "A"
      ["A","B"] -> "A and B"
      ["A","B","C"] -> "A, B and C"
    """
    if not items:
        return ""
    if len(items) == 1:
        return items[0]
    if len(items) == 2:
        return f"{items[0]} and {items[1]}"
    # three or more
    return ", ".join(items[:-1]) + " and " + items[-1]


# ----------------- helpers: phrase classification -----------------

def _split_core_phrases(raw_caption: str) -> list[str]:
    """
    Given a raw caption from t4 build_caption_from_combo, extract core phrases.

    Expected format:
        "a pixel art fantasy rpg character, <core>, four views (front, back, left, right), ..."

    This function:
      - strips the leading boilerplate
      - strips the trailing boilerplate starting from "four views"
      - splits the remaining <core> on ", "
    """
    s = raw_caption.strip()

    # remove leading prefix if present
    prefix = "a pixel art fantasy rpg character, "
    if s.startswith(prefix):
        s_core = s[len(prefix):]
    else:
        s_core = s

    # remove trailing part starting from "four views"
    marker = "four views"
    idx = s_core.find(marker)
    if idx != -1:
        s_core = s_core[:idx].rstrip(", ").strip()

    if not s_core:
        return []

    phrases = [p.strip() for p in s_core.split(",") if p.strip()]
    return phrases


def _is_body_phrase(p: str) -> bool:
    """Heuristic: body / race / skin-related phrases."""
    keywords = [
        "body template",
        "skin",
        "orc",
        "dark elf",
        "skeleton",
        "human",
    ]
    return any(k in p for k in keywords)


def _is_hair_phrase(p: str) -> bool:
    """Heuristic: hair-related phrases."""
    return "hairstyle" in p or "hair" in p


def _is_weapon_phrase(p: str) -> bool:
    """Heuristic: weapon-related phrases."""
    weapon_keywords = [
        "spear",
        "dagger",
        "bow",
        "greatbow",
        "recurve bow",
        "arrows",
        "wand",
        "shield",
        "weapon",
    ]
    return any(k in p for k in weapon_keywords)


# ----------------- helpers: body formatting -----------------

def format_body_phrases(body_phrases: list[str]) -> str:
    """
    Turn raw body phrases like:
      ["male body template", "dark elf", "purple skin"]
    into something more compact and natural like:
      "male dark-elf body, purple skin"

    Handle:
      - gender: male/female
      - race: human / orc / dark elf / skeleton
      - skin tone: any phrase containing "skin"
    """
    if not body_phrases:
        return ""

    gender: str | None = None
    race: str | None = None
    skin_terms: list[str] = []

    for p in body_phrases:
        lp = p.lower()
        if "female body template" in lp:
            gender = "female"
        elif "male body template" in lp:
            gender = "male"
        elif "dark elf" in lp:
            race = "dark-elf"
        elif "orc" in lp:
            race = "orc"
        elif "skeleton" in lp:
            race = "skeleton"
        elif "human" in lp:
            # only set race to human if no more specific race is found
            if race is None:
                race = "human"
        elif "skin" in lp:
            skin_terms.append(p)

    # build core body description
    parts: list[str] = []

    if gender and race:
        if race == "human":
            parts.append(f"{gender} human body")
        elif race == "skeleton":
            parts.append(f"{gender} skeleton body")
        else:
            # dark-elf, orc, etc.
            parts.append(f"{gender} {race} body")
    elif gender and not race:
        parts.append(f"{gender} body")
    elif race and not gender:
        parts.append(f"{race} body")
    else:
        # fallback to raw phrases if cannot structure them
        return ", ".join(body_phrases)

    # add skin terms if any
    if skin_terms:
        # usually only one skin phrase, but join safely
        skin_desc = ", ".join(skin_terms)
        parts.append(skin_desc)

    return ", ".join(parts)


# ----------------- main optimizer -----------------

def optimize_caption(raw_caption: str) -> str:
    """
    Rewrite a raw t4 caption into a shorter, more structured form.

    Rules:
      - Keep all phrases, but group them into:
          body / clothing / hair / gear+weapons
      - Do not attempt to re-derive color/material; just reuse the phrases.
      - Use a compact LoRA-friendly template, with fixed style prefix.
    """
    phrases = _split_core_phrases(raw_caption)

    body_phrases: list[str] = []
    hair_phrases: list[str] = []
    gear_phrases: list[str] = []
    clothing_phrases: list[str] = []

    for p in phrases:
        if _is_body_phrase(p):
            body_phrases.append(p)
        elif _is_hair_phrase(p):
            hair_phrases.append(p)
        elif _is_weapon_phrase(p):
            gear_phrases.append(p)
        else:
            # everything else is treated as clothing / visible equipment
            clothing_phrases.append(p)

    segments: list[str] = []

    # fixed style prefix for LoRA triggering
    segments.append("lpc-style pixel art character")

    if body_phrases:
        body_desc = format_body_phrases(body_phrases)
        if body_desc:
            segments.append(f"with {body_desc}")

    if clothing_phrases:
        cloth_desc = join_with_and(clothing_phrases)
        segments.append(f"wearing {cloth_desc}")

    if hair_phrases:
        hair_desc = ", ".join(hair_phrases)
        segments.append(f"with {hair_desc}")

    if gear_phrases:
        gear_desc = join_with_and(gear_phrases)
        segments.append(f"with {gear_desc}")

    core = ", ".join(segments)

    final = (
        f"{core}, "
        f"4-view sprite sheet (front/back/left/right), "
        f"sharp small pixel art, hard edges, no anti-aliasing"
    )

    return final


# ----------------- main script -----------------

def main():
    if not CAPTION_CSV_IN.exists():
        print("Error: input captions.csv not found:", CAPTION_CSV_IN)
        return

    CAPTION_CSV_OUT.parent.mkdir(parents=True, exist_ok=True)

    print("Reading captions from:", CAPTION_CSV_IN)
    print("Writing optimized captions to:", CAPTION_CSV_OUT)

    rows_out: list[list[str]] = []

    with CAPTION_CSV_IN.open("r", encoding="utf-8", newline="") as f_in:
        reader = csv.DictReader(f_in)
        # expect columns: image_path, text
        for row in reader:
            image_path = row.get("image_path", "").strip()
            raw_caption = row.get("text", "").strip()

            if not image_path:
                continue

            optimized = optimize_caption(raw_caption)
            rows_out.append([image_path, optimized])

    # write output CSV
    with CAPTION_CSV_OUT.open("w", encoding="utf-8", newline="") as f_out:
        writer = csv.writer(f_out)
        writer.writerow(["image_path", "text"])
        writer.writerows(rows_out)

    print("Done. Optimized captions saved to:", CAPTION_CSV_OUT)


if __name__ == "__main__":
    main()
